deploy:
  provider: script
  script: bash ./deploy.sh
  on: master

before_install:
- openssl aes-256-cbc -K $encrypted_bcf4fe04e517_key -iv $encrypted_bcf4fe04e517_iv
  -in deploy.key.enc -out deploy.key -d
- chmod +x ./deploy.sh
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- ssh-keyscan <server> >> ~/.ssh/known_hosts
- git remote add deploy dokku@igpolytech.fr:ancestree-deploy-test
- git config --global push.default simple
