language: node_js
node_js: 12

deploy:
  provider: script
  script: bash ./deploy.sh
  on: master

before_install:
- openssl aes-256-cbc -K $encrypted_bcf4fe04e517_key -iv $encrypted_bcf4fe04e517_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
- chmod +x ./deploy.sh
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- ssh-keyscan igpolytech.fr >> ~/.ssh/known_hosts
- git remote add deploy dokku@igpolytech.fr:ancestree-auth
- git config --global push.default simple
